version: '3'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: frontend.dockerfile
            args:
                FRONTEND_ENV: ${SERVER_BASE_URL}
                SOCKET_ENV: ${SERVER_WEB_SOCKET_URL}
        container_name: frontend
        env_file:
            - .env
        ports:
            - 3000:3000

    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - frontend
        restart: unless-stopped
        ports:
            - 80:80

    backend:
        build:
            dockerfile: backend.dockerfile
            context: ./backend
            args:
                BACKEND_ENV: ${CLIENT_URL}
        container_name: backend
        env_file:
            - .env
        ports:
            - 8080:8080
